sites:
  staging:
    url: http://localhost:8080
    username: praxis-jukimed
    appPassword: elementorcliaccess
staging:
  path: .elementor-cli/staging
  service: wordpress
  url: http://localhost:8080
pagesDir: .elementor-cli/pages
defaultSite: staging
